# This file was generated by GoReleaser. DO NOT EDIT.
cask "opndossier" do
  version "1.7.2"

  on_macos do
    sha256 "da93941c318129a1aac4671c4176f1bd1a6880368eb23bc64294551c95b899eb"
    url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "fd5a60914622227ce990a784d8c0824fd054eaa171edfe6654fa0ecbc8719da1"
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f68c1580e73366f2cbcd9ecfa88f03d076eb957451355580aba504c9e3e71d3"
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Linux_x86_64.tar.gz"
    end
  end

  name "opndossier"
  desc "OPNsense configuration documentation and compliance auditing tool"
  homepage "https://github.com/EvilBit-Labs/opnDossier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opndossier"
  manpage "man/opndossier.1"
  bash_completion "completions/opndossier.bash"
  fish_completion "completions/opndossier.fish"
  zsh_completion "completions/opndossier.zsh"

  # No zap stanza required
end
