# This file was generated by GoReleaser. DO NOT EDIT.
cask "opndossier" do
  name "opndossier"
  desc "OPNsense configuration documentation and compliance auditing tool"
  homepage "https://github.com/EvilBit-Labs/opnDossier"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opndossier"
  bash_completion "completions/opndossier.bash"
  zsh_completion "completions/opndossier.zsh"
  fish_completion "completions/opndossier.fish"

  on_macos do
    on_intel do
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Darwin_x86_64.tar.gz"
      sha256 "a4a12605e8243cd313e350a0cef84ff18cbfae5fbd877169857d9979258c4f90"
    end
    on_arm do
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Darwin_arm64.tar.gz"
      sha256 "add274272c778710e0cb732e705cb21ad683b3dee3a22ab7ea7ffa96cc3eeca1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Linux_x86_64.tar.gz"
      sha256 "7c52fe507743201c9c9a4fe5982fe58b9d2983c819ee13f7488d182b3d64384d"
    end
    on_arm do
      url "https://github.com/EvilBit-Labs/opnDossier/releases/download/v#{version}/opnDossier_Linux_arm64.tar.gz"
      sha256 "6e17bff4cbdad71bea88ded14cefaafe03d2356277c9761389e5eb814ccffa29"
    end
  end

  # No zap stanza required
end
