# This file was generated by GoReleaser. DO NOT EDIT.
cask "unifi-extract" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "68562ea90c4a47151812837b929ba30e710d3aa8f524b31b5f137ee05a42b3c7"
      url "https://github.com/EvilBit-Labs/unifi_extract/releases/download/v#{version}/unifi-extract_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8c3f21c0ea33a87e673f9f92705b5dad222016f10071ab0f432304891e25552b"
      url "https://github.com/EvilBit-Labs/unifi_extract/releases/download/v#{version}/unifi-extract_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dea67a16d319e4541730e298f3ed5fd1a6914c8040e36e2a9384e9761c31aa4e"
      url "https://github.com/EvilBit-Labs/unifi_extract/releases/download/v#{version}/unifi-extract_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38d8f8d01c238cf415320e303bbc69402d981280ffa96b94688be31734c8284b"
      url "https://github.com/EvilBit-Labs/unifi_extract/releases/download/v#{version}/unifi-extract_Linux_arm64.tar.gz"
    end
  end

  name "unifi-extract"
  desc "Offline CLI to decrypt and explore UniFi backup files (.unf/.unifi)"
  homepage "https://github.com/EvilBit-Labs/unifi_extract"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unifi-extract"

  # No zap stanza required

end
